### ISSUE TITLE
Shows "NaN" when navigating through multiple entities 

### ISSUE THREAD

**Issue by albertocottica** [opencarecc/graph-ryder-dashboard#10]
Click on one post in the list on the right, the frame opens where we can read the full text of the post. Click on a second one, this happens (he post in question is this: https://edgeryders.eu/en/practical-resilience/mission_case/response-vinays-europes-new-war). It seems that the dashboard always responds well to the first request to see a post, and always badly to requests after the first one. 

![graphryder_missing_reference](https://cloud.githubusercontent.com/assets/1976806/23435647/47a3f206-fe08-11e6-8a06-dc82fbe3b825.jpg)

**Comment by albertocottica** [comment]
Then same thing happens with other kinds of entities, like codes.

**Comment by jason-vallet** [comment]
Ok, this one is a bit harder to address. After a lot of testing on Firefox, this behaviour never occurred even a single time. Then I tried the same on Chromium and, indeed, the issue appears from time to time (but mostly on the first try to consult a content). Maybe it is the same on Safari and Edge?

My tests on Chromium were mostly focussed on checking if the overall appearance of the views was similar across the browsers, so it slipped right under my nose. Some versions of Chrome seems to have known shortcomings getting the content via promises, see this previous [bug report](https://github.com/angular/angular.js/issues/15013). I will look into it.

**Comment by jason-vallet** [comment]
Ok, its fixed. I went looking for the error way too far instead of focusing on what should have been obvious. When you hear hoofbeats...
