### ISSUE TITLE
Hardcoded values of co-occurrence you can select from

### ISSUE THREAD

**Issue by albertocottica** [opencarecc/graph-ryder-dashboard#22]
The dashboard allows filtering by number of co-occurrences, but the value passed to the filter is limited to `[1, 8]`. The maximum number of co-occurrences is currently 40.

Can we have a way to select the filtering value that is independent of the data? Tomorrow GraphRyder might be used by Aalborg University, with hundreds of thousands of co-occurrences.

**Comment by jason-vallet** [comment]
Done. The value is now selected using a spinner.
