### ISSUE TITLE
Social network broken?

### ISSUE THREAD

**Issue by guywiz** [opencarecc/graph-ryder-dashboard#27]
Discussing the migration to Discourse with Jason, we realize that the social network -- as it is computed now -- cannot be recovered from the thread structure in Discourse. From what I understand -- hopefully I am wrong -- in Discourse all comments are comments to the initial post and no information is stored as whether a comment is a comment to a previous comment.

A direct consequence of this is that the social interaction we may infer is a clique indicating a bunch of people were involved in a same thread -- so the overall social network would be obtained by aggregating all these cliques. This would produce a radically different structure that the one we are looking at now.

Of course, this is only hypothetical since we have not yet seen any Discourse data.I guess you guys are preparing views that can be used from graph-ryder.

?

**Comment by albertocottica** [comment]
Not only that: we are porting the entire OpenEthno dataset, _and_ porting
OpenEthno itself onto Discourse. Should be another week before we give you
access to the new APIs.

**Comment by albertocottica** [comment]
Closing: APIs fully operational.
