### ISSUE TITLE
Make a GraphRyder version that works with the new Edgeryders platform 

### ISSUE THREAD

**Issue by albertocottica** [opencarecc/graph-ryder-dashboard#29]
Content can be accessed via Discourse JSON APis: http://docs.discourse.org/

Ethno codes/annotations need bespoke access. The issue governing this is here: https://github.com/edgeryders/discourse/issues/97

I created some functions and used them to update my "Rapid social networks" Tulip script. It only accesses primary data (content). Of course my code is going to suck, but @guywiz wanted to see it. 

* [This script](https://github.com/opencarecc/rapid-social-networks/blob/master/Discourse/Code/discourse_OC_network_2.py) creates the OpenCare social network.
* It uses [this collection of functions](https://github.com/opencarecc/rapid-social-networks/blob/master/Discourse/Code/discourse_API_Edgeryders.py).

**Comment by guywiz** [comment]
Can't run the code, I need to import the discourse_API_Edgeryders package -- what does that correspond to? A series of home-made functions?

**Comment by albertocottica** [comment]
Yes, check the second link in the issue text.

**Comment by albertocottica** [comment]
@jason-vallet API access to annotations now available on Edgeryders: https://github.com/edgeryders/discourse/issues/97#issuecomment-338816804
