### ISSUE TITLE
[related] Export a list of user IDs from the OLD dataset

### ISSUE THREAD

**Issue by albertocottica** [opencarecc/graph-ryder-dashboard#33]
Jason, this is kind of a weird request, but it should not take you more than 45 mins. 

I would like you to start from your graph database, populated with data from the Drupal platform (this is what I have today on my GraphRyder dashboard) and export a list of its 282 usernames and user IDs, in CSV or JSON or whatever you want. That's it. 

Possible?

**Comment by jason-vallet** [comment]
Hi, the route http://164.132.58.138:5000/users should give you what you are
looking for: a json with ids and labels.

**Comment by albertocottica** [comment]
Great, thanks!
