### ISSUE TITLE
Toggle show labels in the co-occurrences graph ("tag-tag full")

### ISSUE THREAD

**Issue by albertocottica** [opencarecc/graph-ryder-dashboard#4]
It would be nice to have a way to quickly add labels to see what stands out. At the moment I explore this graph with a lot of mouseover, but in that way it is more difficult to get a feel from the hierarchy of the codes.

**Comment by jason-vallet** [comment]
I've added a check-box to force display the tags' labels and a slider for some finer control over it. Overall, the priority still depends of each node size, so big nodes show their label first while the small nodes' labels come last.

**Comment by albertocottica** [comment]
Works great, @jason-vallet, thanks. Closing.
