### ISSUE TITLE
The search string does not accept ethno codes 

### ISSUE THREAD

**Issue by albertocottica** [opencarecc/graph-ryder-dashboard#9]
I can see the role of http://164.132.58.138:9000/#/dashboard/tagView as a way to quickly call up a code and its neighbours. It would be useful to be able to search it.

**Comment by jason-vallet** [comment]
This is actually possible but sometimes the ethno codes do not show up in the search results. Refreshing the page should fix the issue.

I still leave it as a bug, but a low priority one.

**Comment by guywiz** [comment]
I'm writing to get this bug a higher priority. Not being able to search using ethno codes can be a problem.

It seems to me some codes allow to be searched (mental health), others don't (trauma). I had the impression the number of listed items was kept to a maximum of 8. If it's the case, it's kinda bad. You certainly need/must to rank the items that are listed, but you should give access to the whole list of relevant items -- only making a few visible, through a scrollable list, for instance.

**Comment by jason-vallet** [comment]
Issue merged with #19 All fields should now work properly.
